## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
9960,14837,1.286884,-0.124610,0.148283,-0.259343,0.248357,0.896718,-0.626627,0.227693,1.618678,...,-0.381864,-0.904515,-0.027985,-1.743540,0.090885,0.870425,-0.084116,-0.022744,12.18,0.0
9961,14854,1.318742,0.496408,0.114876,0.695262,0.170133,-0.537180,0.025492,-0.272931,1.267298,...,-0.484943,-1.111176,0.028259,-0.549934,0.328634,0.106061,-0.046154,0.017304,1.78,0.0
9962,14857,1.241757,0.419587,0.806183,0.894811,-0.507886,-1.118126,0.018908,-0.343335,1.210781,...,-0.379396,-0.817785,0.181425,0.662879,0.172535,0.033636,-0.051084,0.017208,1.29,0.0
9963,14861,1.304800,-0.052885,0.415235,-0.081725,-0.223525,0.097752,-0.561240,0.067228,1.617203,...,-0.379597,-0.929204,0.020955,-0.877006,0.084384,0.807465,-0.099851,-0.015404,4.72,0.0
9964,14864,-1.747939,3.712444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9965 entries, 0 to 9964
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    9965 non-null   int64
 1   V1      9965 non-null   float64
 2   V2      9965 non-null   float64
 3   V3      9964 non-null   float64
 4   V4      9964 non-null   float64
 5   V5      9964 non-null   float64
 6   V6      9964 non-null   float64
 7   V7      9964 non-null   float64
 8   V8      9964 non-null   float64
 9   V9      9964 non-null   float64
 10  V10     9964 non-null   float64
 11  V11     9964 non-null   float64
 12  V12     9964 non-null   float64
 13  V13     9964 non-null   float64
 14  V14     9964 non-null   float64
 15  V15     9964 non-null   float64
 16  V16     9964 non-null   float64
 17  V17     9964 non-null   float64
 18  V18     9964 non-null   float64
 19  V19     9964 non-null   float64
 20  V20     9964 non-null   float64
 21  V21     9964 non-null   float64
 22  V22     9964 non-null   float64
 23  V23     9964 non-null   float64
 24  V24     9964 non-null   float64
 25  V25     9964 non-null   float64
 26  V26     9964 non-null   float64
 27  V27     9964 non-null   float64
 28  V28     9964 non-null   float64
 29  Amount  9964 non-null   float64
 30  Class   9964 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 2.4 MB

In [6]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
credit_card_data['Class'].value_counts()

0.0    9926
1.0      38
Name: Class, dtype: int64

### *This* Dataset is highly unblanced

## 0 --> Normal Transaction

## 1 --> fraudulent transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(9926, 31)
(38, 31)

In [10]:
legit.Amount.describe()

count    9926.000000
mean       62.919501
std       184.041297
min         0.000000
25%         5.172500
50%        15.950000
75%        51.067500
max      7712.430000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count      38.000000
mean       75.730526
std       304.521215
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [12]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,5921.607697,-0.235577,0.266833,0.934388,0.239735,-0.041743,0.140925,-0.057661,-0.069971,0.813003,...,0.026103,-0.055139,-0.152043,-0.033460,0.023142,0.087567,0.107554,0.003624,0.001701,62.919501
1.0,9063.157895,-1.796662,3.810809,-6.415255,5.618146,-1.247563,-2.111328,-3.777261,1.150469,-2.276505,...,0.467700,0.741934,-0.164628,-0.024469,-0.371142,0.018063,0.310646,0.525443,0.355663,75.730526

*Under*-Sampling

Number of Fraudulent Transactions --> 38

> Indented block



1.   List item
2.   List item

In [14]:
legit_sample = legit.sample(n=38)

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6055,6861,-0.418489,1.093747,1.283546,0.031716,0.495387,0.034199,0.414728,0.166145,0.682993,...,-0.355873,-0.728583,-0.013434,-0.427057,-0.248403,0.066538,0.228009,0.075053,6.23,0.0
5012,4593,-1.405923,0.633797,2.699134,1.264805,0.696891,0.959094,0.614487,-2.917074,3.089734,...,1.070873,-0.180895,-0.079623,0.009138,-0.277962,-0.473304,-1.493479,-1.114956,15.00,0.0
6714,8396,-2.035420,-1.517940,2.261632,-2.078025,0.278908,-0.800973,-0.072727,-0.081387,2.870886,...,-0.078544,0.536746,0.646624,-0.035814,0.721343,-0.097169,-0.111724,-0.258491,71.07,0.0
5035,4648,-1.363699,0.133793,-0.428835,0.680824,2.881822,3.388252,-0.754169,1.369784,0.744377,...,-0.127601,-0.440415,-0.118872,0.959566,0.137290,-0.284393,0.275152,-0.019020,27.42,0.0
1705,1317,-1.401282,1.441452,1.084768,-0.750454,-0.491807,-0.793817,0.267991,0.537277,-0.038416,...,-0.146903,-0.294730,-0.004162,0.541832,-0.154576,0.274771,0.382995,0.230803,1.00,0.0

In [17]:
new_dataset['Class'].value_counts()

0.0    38
1.0    38
Name: Class, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,5412.763158,-0.563265,-0.180422,0.979226,-0.037911,0.232204,0.266952,-0.059950,0.010823,0.721712,...,-0.039215,0.080206,-0.055611,0.069662,0.021580,0.032764,0.144094,-0.001952,0.013953,92.268684
1.0,9063.157895,-1.796662,3.810809,-6.415255,5.618146,-1.247563,-2.111328,-3.777261,1.150469,-2.276505,...,0.467700,0.741934,-0.164628,-0.024469,-0.371142,0.018063,0.310646,0.525443,0.355663,75.730526

Splitting the data into Features & Targets

In [19]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [20]:
print(X)

       Time        V1        V2         V3         V4        V5        V6  \
6055   6861 -0.418489  1.093747   1.283546   0.031716  0.495387  0.034199
5012   4593 -1.405923  0.633797   2.699134   1.264805  0.696891  0.959094
6714   8396 -2.035420 -1.517940   2.261632  -2.078025  0.278908 -0.800973
5035   4648 -1.363699  0.133793  -0.428835   0.680824  2.881822  3.388252
1705   1317 -1.401282  1.441452   1.084768  -0.750454 -0.491807 -0.793817
...     ...       ...       ...        ...        ...       ...       ...
9035  12597 -2.589617  7.016714 -13.705407  10.343228 -2.954461 -3.055116
9179  13126 -2.880042  5.225442 -11.063330   6.689951 -5.759924 -2.244031
9252  13323 -5.454362  8.287421 -12.752811   8.594342 -3.106002 -3.179949
9487  14073 -4.153014  8.204797 -15.031714  10.330100 -3.994426 -3.250013
9509  14152 -4.710529  8.636214 -15.496222  10.313349 -4.351341 -3.322689

             V7        V8        V9  ...       V20       V21       V22  \
6055   0.414728  0.166145  0.682993  ...  0.057355 -0.355873 -0.728583
5012   0.614487 -2.917074  3.089734  ... -0.448206  1.070873 -0.180895
6714  -0.072727 -0.081387  2.870886  ... -0.232842 -0.078544  0.536746
5035  -0.754169  1.369784  0.744377  ...  0.454818 -0.127601 -0.440415
1705   0.267991  0.537277 -0.038416  ...  0.156093 -0.146903 -0.294730
...         ...       ...       ...  ...       ...       ...       ...
9035  -9.301289  3.349573 -5.654212  ...  1.488855  1.887738  0.333998
9179 -11.199975  4.014722 -3.429304  ...  1.191444  2.002883  0.351102
9252  -9.252794  4.245062 -6.329801  ...  1.305862  1.846165 -0.267172
9487 -10.415698  4.620804 -5.711248  ...  1.412625  1.976988  0.256510
9509 -10.788373  5.060381 -5.689311  ...  1.434240  1.990545  0.223785

           V23       V24       V25       V26       V27       V28  Amount
6055 -0.013434 -0.427057 -0.248403  0.066538  0.228009  0.075053    6.23
5012 -0.079623  0.009138 -0.277962 -0.473304 -1.493479 -1.114956   15.00
6714  0.646624 -0.035814  0.721343 -0.097169 -0.111724 -0.258491   71.07
5035 -0.118872  0.959566  0.137290 -0.284393  0.275152 -0.019020   27.42
1705 -0.004162  0.541832 -0.154576  0.274771  0.382995  0.230803    1.00
...        ...       ...       ...       ...       ...       ...     ...
9035  0.287659 -1.186406 -0.690273  0.631704  1.934221  0.789687    1.00
9179  0.795255 -0.778379 -1.646815  0.487539  1.427713  0.583172    1.00
9252 -0.310804 -1.201685  1.352176  0.608425  1.574715  0.808725    1.00
9487  0.485908 -1.198821 -0.526567  0.634874  1.627209  0.723235    1.00
9509  0.554408 -1.204042 -0.450685  0.641836  1.605958  0.721644    1.00

[76 rows x 30 columns]

In [21]:
print(Y)

6055    0.0
5012    0.0
6714    0.0
5035    0.0
1705    0.0
       ...
9035    1.0
9179    1.0
9252    1.0
9487    1.0
9509    1.0
Name: Class, Length: 76, dtype: float64

## Split the data into Training data & Testing Data

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(76, 30) (60, 30) (16, 30)

Model Training

Logistic Regression

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy score

In [26]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0

In [28]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  1.0